### ISSUE TITLE
Update for MyMonero in yarn.lock

### ISSUE THREAD

**Issue by hosekhoshtaghaza** [EdgeApp/edge-react-gui#1038]
Yarn points to github.com/Airbitz/mymoneo-core-js.git however this now seems to be located at github.com/EdgeApp/mymonero-core-js.git.

**Comment by paullinator** [comment]
This was fixed in commit

https://github.com/EdgeApp/edge-react-gui/commit/05ef9eaa028c7febac1ee200ac1e34b38fb8c50d#diff-8ee2343978836a779dc9f8d6b794c3b2
