### ISSUE TITLE
UI bug: TX list is covered by footer bar on Android

### ISSUE THREAD

**Issue by NukeManDan** [EdgeApp/edge-react-gui#1160]
:crossed_fingers: this is the right place to put this:

I am unable to view (although the div is visible enough to click) the last entry in all wallets - it is covered by the footer bar with the `wallet, request, ...` As seen here: 

![image](https://user-images.githubusercontent.com/35669742/51001084-265d5900-14ec-11e9-9ced-f96d7467f438.png)

Device: Android 7.1.1 , Moto Play G

**Comment by kylanhurt** [comment]
@NukeManDan Can you verify whether or not this is still an issue on 1.7.1?
