### ISSUE TITLE
Consider removing dependencies on Google Play Services

### ISSUE THREAD

**Issue by jcalfee** [EdgeApp/edge-react-gui#1259]
Could you please consider removing the dependencies on Google Play Services.  Services like f-droid.org and "The Yalp Store" make it possible to use Android without a Google Play account and therefore avoids much of the illegal spying and privacy problems introduced by Google.  When I started the Edge wallet on Android it unfortunately showed me a dialog saying that it depends on Google Play services and stated that it will not work.

On another note, thank you for notifying me in advanced about this before I tried to deposit funds..

**Comment by paullinator** [comment]
Hi James. Note that the popup modal about the app not working with Google Play gets generated by an included SDK, but it is not actually correct. The app will continue to work just fine even if you don't have Google Play services. We're not sure why to popup shows and we're researching how to get it removed as the app should function just fine without it.
