### ISSUE TITLE
Won't connect to Bitcoin Electrum server over TLS

### ISSUE THREAD

**Issue by stiell** [EdgeApp/edge-react-gui#1433]
I'm trying to specify a custom node using an electrums:// URL, as suggested in the empty input field. I press save, then log out and in again, then try to resync my Bitcoin wallet. The wallet does not connect to the custom node, and the progress bar along the top of the screen is stuck around 10%.

If I try the same using an electrum:// URL, i.e. unsecured, it will connect.

Looking at the edge-currency-bitcoin code, it seems to ignore electrums:// entries.

**Comment by paullinator** [comment]
Due to limitations of react-native, only electrum wss sockets are supported. you can add `electrumwss:...` as a server
