### ISSUE TITLE
Exchange rates delay

### ISSUE THREAD

**Issue by hosekhoshtaghaza** [EdgeApp/edge-react-gui#1512]
The exchangeRates action seems to be returning all 0's for roughly 2 minutes after initial login, leaving the wallet on getting exchange rates. This behaviour has developed/worsened over the past couple of days.

**Comment by paullinator** [comment]
This is fixed in the latest version. It’s already available on android but waiting for apples approval on iOS

**Comment by hosekhoshtaghaza** [comment]
Thanks for such a quick reply Paul. I am just trying to fix this issue in our app. Do you have any insight on which commit/s patched this as I can't see anything relating to the exchangeRates prop/account.exchangeCache being changed in recent days? I tried updating edge-currency-accountbased to 0.19 but no joy.

**Comment by paullinator** [comment]
This commit fixes the problem

e2301c288a4ddf50d15fc8f3203aee35b05eda39

**Comment by hosekhoshtaghaza** [comment]
Thank you Paul!! Life saver.
