### ISSUE TITLE
Denomination missing from getWalletHistory

### ISSUE THREAD

**Issue by KShared** [EdgeApp/edge-react-gui#1872]
Hi

I am trying to implement the Edge app api and am having issues figuring out the denomination of the nativeAmount field. It looks like users can choose their denominations in Edge but how can app developers see the default denomination for that currency?

It would be great if you could update the getWalletHistory() method to also give back the default denomination/multiplier for the currency. By default I mean the denomination that is used for the currency on blockexplorers and other services (not necessarily the one chosen by the user).

Thanks!

**Comment by paullinator** [comment]
The denomination is part of the currency info in the wallet object. You can use that with the native amount to determine the primary denomination of the wallet.
