### ISSUE TITLE
API key for developer...

### ISSUE THREAD

**Issue by Mattiell0X** [EdgeApp/edge-react-gui#2338]
Hello guys,
I would like to know if I can add the estellar blockchain to this wallet to use my own tokens.
Here in Brazil we have a project that where we need a wallet with a stellar wallet to list our token, I would also like to know if I can use my brand on the wallet.
What we are doing is creating a community bank in order to make a blockchain-based digital account available to low-income people or unbanked.
I saw that also to use as a developer you need an api key ...
I tried many times to log in to this portal https://developer.airbitz.co/login
simple is not possible I installed the egge wallet and arbitz wallet and neither of them read the portal's qrcode.
Can you make an api key available to me?
I sent an email, but got no answers ....

**Comment by paullinator** [comment]
Please contact info@edge.app for an api key now
