### ISSUE TITLE
pull to refresh on transaction list breaks

### ISSUE THREAD

**Issue by wolverineks** [EdgeApp/edge-react-gui#2412]
Steps to reproduce:
1. navigate to transaction list
2. pull to refresh

OS: Android

version: 2.0.0
build: 21012702

**Comment by paullinator** [comment]
Can you describe what you mean by break?

**Comment by wolverineks** [comment]
pull to refresh causes a transaction search
if no transactions, there is no done button to get out of search

**Comment by paullinator** [comment]
The issues with no transactions is known and we have a task to fix it. But otherwise, pulling down to search is intended behavior. We don’t have a pull to refresh so we hijacked that functionality to auto focus into the search field. Similar functionality exists in iOS.
