### ISSUE TITLE
Coin Control

### ISSUE THREAD

**Issue by trymeouteh** [EdgeApp/edge-react-gui#3106]
Please add a setting within the wallet to enable/disable coin control and have it enabled by default.

With this feature it will make Edge wallet more private to prevent 2 or more addresses being used on sending a coin to prevent anyone on the blockchain determining if two addresses are owned by the same person.

**Comment by paullinator** [comment]
Coin control is a very advanced feature and requires extensive ui and testing to implement. While we agree on the value of the feature, it’s not quite suited to our target audience. 

Thanks for your input
