### ISSUE TITLE
Include apk with releases

### ISSUE THREAD

**Issue by Andrewskiz** [EdgeApp/edge-react-gui#3992]
It would be great if you provided an apk on the Github releases page, since the apk on the main page does not specify the version and there is no way to be notified when there is an update.

**Comment by Sami32** [comment]
Sadly i doesn't be on their roadmap :-(

**Comment by Andrewskiz** [comment]
What alternative is that? I've since switched to Cake Wallet since Edge interface keeps getting more bloated and advertising laden.

**Comment by Sami32** [comment]
@Andrewskiz Kraken wallet
https://github.com/krakenfx/wallet/releases

**Comment by paullinator** [comment]
> It would be great if you provided an apk on the Github releases page, since the apk on the main page does not specify the version and there is no way to be notified when there is an update.

Thanks for the suggestion. We'll start doing that with the next release. @rjrs2k please put APKs on github

**Comment by rjrs2k** [comment]
@paullinator Done this has been taken care of in our latest 4.7.0 release which includes the APK on Github as you can see here: https://github.com/EdgeApp/edge-react-gui/releases/tag/v4.7.0. 

I will be doing this going forward and thank you for the suggestion! @Andrewskiz
