### ISSUE TITLE
Add static value for com.bugsnag.android.BUILD_UUID to AndroidManifest.xml

### ISSUE THREAD

**Issue by emanuelb** [EdgeApp/edge-react-gui#4145]
From decompiled APK on edge version 3.6.0 downloaded from website it shows in AndroidManifest.xml the line:
```xml
<meta-data android:name="com.bugsnag.android.BUILD_UUID" android:value="fd7bc623-0f99-40f8-b23d-527c1483d077"/>
```
while building the app from the same tag will generate different random BUILD_UUID such as:
```xml
 <meta-data android:name="com.bugsnag.android.BUILD_UUID" android:value="992986e6-5134-4700-82b9-58fb16e2a130"/>
```

trying to set it to static value in compilation via command
```shell
sed -i '/^\s*<\/application>\s*/i <meta-data android:name="com.bugsnag.android.BUILD_UUID" android:value="fd7bc623-0f99-40f8-b23d-527c1483d077"/>' android/app/src/main/AndroidManifest.xml; 
```

will add the value but the resulted AndroidManifest.xml will differ as it will be added in different place in the file (not before after the tag `<service android:name="androidx.room.MultiInstanceInvalidationService" android:exported="false" android:directBootAware="true"/>` as it's suppose to be)

fix:

Add the `com.bugsnag.android.BUILD_UUID` to the repo in AndroidManifest.xml file with value that will be changed between branches/tags, thus helps RB is it wont randomly be generated.

From https://docs.bugsnag.com/api/android-mapping-upload/#for-proguard

> buildUUID (optional) - a UUID to identify this builds. This is required if you build multiple different apps with the same appId and versionCode. If you use this, you’ll also need to set the com.bugsnag.android.BUILD_UUID value in your AndroidManifest.xml.`

**Comment by paullinator** [comment]
Bugsnag is deprecated in favor of Sentry which has an open source, self hosted backend.
