### ISSUE TITLE
Static versionCode & versionName instead of updated for each tag

### ISSUE THREAD

**Issue by emanuelb** [EdgeApp/edge-react-gui#4146]
in AndroidManifest.xml file of generated APK that is locally built the versionCode is 21000000 and versionName is 99.99.99
cause of:

https://github.com/EdgeApp/edge-react-gui/blob/67e9597452cac52aa7062126d4f2713a3120fe22/android/app/build.gradle#L135-L136

while downloading APK from Google Play or Website will have values like:

versionCode: 23032902
versionName: 3.6.0

and it will be changed for each version.

static versionCode is problematic cause:

1. won't enable manual apk update of locally built apks (will need to remove apk and then install it again) as all built APKs will have the same version.
2. fdroid will detect it as error and for workaround will use other assigned number for it that they manage unless it will be specified in the recipe which wont be automatic (but can be if values are updated in the repo and are accurate for each git tag)

thus it make sense to update this value in repo to the correct one used in upcoming version before releasing new app, so for each git checkout of git tag, the values will be accurate for that version.

same apply for versionName to change it from 99.99.99 to the currently release like 3.6.0 and in every new git tag change it again

**Comment by paullinator** [comment]
The static versions are meant to be updated by the build scripts. https://github.com/EdgeApp/edge-react-gui/blob/develop/scripts/deploy.ts is meant to create a production build and updates versions.
