### ISSUE TITLE
Unable to update Edge Wallet

### ISSUE THREAD

**Issue by jahway603** [EdgeApp/edge-react-gui#4227]
I am unable to receive updates for Edge Wallet as I do not sacrifice myself to the g00gle g0ds. What alternative update methods does the Edge App team have to update Edge Wallet to the latest version?

I see that Issue https://github.com/EdgeApp/edge-react-gui/issues/1767 is one method to fix my Edge Wallet updating issue and was filed Dec 24, 2019

**Comment by paullinator** [comment]
You should be able to download the latest Android APK via https://edge.app/app
