### ISSUE TITLE
work in development

### ISSUE THREAD

**Issue by Amatack** [EdgeApp/edge-react-gui#5361]
Hi, I want to implement support for the eCash cryptocurrency within their wallet, I get from this error in the console after entering my pin for the first time on the app: 

LOG {
"logEvent": {
"event": "Signup_Create_Light_Account",
"params": {
"edgeVersion": "99.99.99",
"buildNumber": "21000000",
"isFirstOpen": "false",
"deviceId": "ddce4507-5880-4e91-b797-8e65cadda2cd",
"firstOpenEpoch": 1731627539043,
"error": "Error: Invalid API key",
"svar_signupCaptcha": "withCaptcha", 
"svar_uspSigninCta": "alreadyHaveAccount",
 "notificationStatus": "granted"
 }
 }
}

Maybe I need to enter the API key, apparently my env.json looks like this: 

{
 "EDGE_API_KEY": "",
 "COINGECKO_API_KEY": "a0000000000000000000000000000000",
 "IP_API_KEY": "",
 "SENTRY_DSN_URL": "SENTRY_DSN_URL",
 "SENTRY_MAP_UPLOAD_URL": "SENTRY_MAP_UPLOAD_URL",
 "SENTRY_MAP_UPLOAD_AUTH_TOKEN": "SENTRY_MAP_UPLOAD_AUTH_TOKEN",
 "SENTRY_ORGANIZATION_SLUG": "SENTRY_ORGANIZATION_SLUG",
 "SENTRY_PROJECT_SLUG": "SENTRY_PROJECT_SLUG",
 "ACTION_QUEUE": {
 "debugStore": false,
 "enableDryrun": true,
 "pushServerUri": "https://push.edge.app",
 "mockMode": false
 },
 "PLUGIN_API_KEYS": {},
 "WYRE_CLIENT_INIT": {
 "baseUri": "https://api.sendwyre.com"
 },
 "AZTECO_API_KEY": null,
 "STAKEKIT_API_KEY": null,
 "KILN_TESTNET_API_KEY": null,
 "KILN_TESTNET_ACCOUNT_ID": null,
 "KILN_MAINNET_API_KEY": null,
 "KILN_MAINNET_ACCOUNT_ID": null,
 "UNSTOPPABLE_DOMAINS_API_KEY": null,
 "ARBITRUM_INIT": false,
 "AMOY_INIT": false,
 "ALGORAND_INIT": true,
 "AVALANCHE_INIT": false,
 "AXELAR_INIT": true,
 "BASE_INIT": false,
 "BINANCE_SMART_CHAIN_INIT": false,
 "BITCOIN_INIT": false,
 "BITCOINCASH_INIT": false,
 "CARDANO_INIT": false,
 "CARDANO_TESTNET_INIT": false,
 "CELO_INIT": false,
 "CHANGE_NOW_INIT": false,
 "CHANGEHERO_INIT": false,
 "COREUM_INIT": false,
 "COSMOSHUB_INIT": false,
 "DASH_INIT": false,
 "DIGIBYTE_INIT": false,
 "DOGE_INIT": false,
 "ETHEREUM_INIT": false,
 "ETHEREUM_POW_INIT": false,
 "EXOLIX_INIT": false,
 "FANTOM_INIT": false,
 "FIO_INIT": true,
 "FILECOINFEVM_INIT": false,
 "FILECOINFEVM_CALIBRATION_INIT": false,
 "FILECOIN_INIT": false,
 "GROESTLCOIN_INIT": false,
 "GODEX_INIT": false,
 "HOLESKY_INIT": false,
 "HEDERA_INIT": true,
 "LIBERLAND_INIT": true,
 "LIFI_INIT": false,
 "LITECOIN_INIT": false,
 "LETSEXCHANGE_INIT": false,
 "MONERO_INIT": false,
 "OPTIMISM_INIT": false,
 "OSMOSIS_INIT": false,
 "PULSECHAIN_INIT": false,
 "POLKADOT_INIT": true,
 "POLYGON_INIT": false,
 "INIT_RANGE": false,
 "RSK_INIT": false,
 "SEPOLIA_INIT": false,
 "SIDESHIFT_INIT": false,
 "SOLANA_INIT": false,
 "SPOOKY_SWAP_INIT": false,
 "SWAPUZ_INIT": false,
 "MAYA_PROTOCOL_INIT": false,
 "THORCHAIN_INIT": false,
 "SWAPKIT_INIT": false,
 "TOMB_SWAP_INIT": false,
 "WALLET_CONNECT_INIT": false,
 "XRPDEX_INIT": false,
 "ZCOIN_INIT": false,
 "0XGASLESS_INIT": false,
 "ZKSYNC_INIT": false,
 "APP_CONFIG": "edge",
 "ENABLE_STAKING": true,
 "ENABLE_VISA_PROGRAM": false,
 "BETA_FEATURES": false,
 "KEYS_ONLY_PLUGINS": {},
 "USE_FAKE_CORE": false,
 "USE_FIREBASE": true,
 "USE_WELCOME_SCREENS": true,
 "YOLO_DEEP_LINK": null,
 "YOLO_PASSWORD": null,
 "YOLO_PIN": null,
 "YOLO_USERNAME": null,
 "ALLOW_DEVELOPER_MODE": true,
 "DEV_TAB": false,
 "DEBUG_CORE": false,
 "DEBUG_CURRENCY_PLUGINS": false,
 "DEBUG_PLUGINS": false,
 "DEBUG_ACCOUNTBASED": false,
 "DEBUG_EXCHANGES": false,
 "DEBUG_VERBOSE_ERRORS": false,
 "DEBUG_THEME": false,
 "MUTE_CONSOLE_OUTPUT": [],
 "ENABLE_FIAT_SANDBOX": false,
 "ENABLE_MAESTRO_BUILD": false,
 "ENABLE_REDUX_PERF_LOGGING": false,
 "LOG_SERVER": null,
 "THEME_SERVER": {
 "host": "localhost",
 "port": "8008"
 },
 "EXPERIMENT_CONFIG_OVERRIDE": {}
}

after installing the dependencies with yarn

**Comment by samholmes** [comment]
Hello, what error message do you receive?

**Comment by swansontec** [comment]
Edge-core-js used to treat `""` as the default API key. However, we recently introduced a bug where `""` no longer works, but `undefined` does. So, editing EdgeCoreManager.ts, and replacing `EDGE_API_KEY` with `undefined` will get you up & running again. I have already created a task in our internal scheduling system to get this bug fixed.

**Comment by swansontec** [comment]
The fix is merged to `develop`, so we should be good now.
