### ISSUE TITLE
Project build Windows

### ISSUE THREAD

**Issue by Fliego** [EdgeApp/edge-react-gui#600]
Windows x64
yarn 1.6.0
npm 5.6
Node 8.11.1
Android SDK v26.0.2
Windows build tools (v140) + Python27
OpenSSL 1.0.2o 27 Mar 2018

If I try to install packages via npm and "npm run android:release-install" then other issues appear

> :app:mergeReleaseResources
> :app:bundleReleaseJsAndAssets
> Scanning folders for symlinks in C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui\node_modules (116ms)
> Scanning folders for symlinks in C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui\node_modules (129ms)
> Loading dependency graph, done.
> warning: the transform cache was reset.
> 
> Unable to resolve module `bcoin` from `C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui\node_modules\edge-currency-bitcoin\lib\index.js`: Module does not exist in the module map or in these directories:
>   C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui\node_modules
> 
> This might be related to https://github.com/facebook/react-native/issues/4968
> To resolve try the following:
>   1. Clear watchman watches: `watchman watch-del-all`.
>   2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
>   3. Reset Metro Bundler cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
> 
> :app:bundleReleaseJsAndAssets FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:bundleReleaseJsAndAssets'.
> > Process 'command 'cmd'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3m 14s
> 228 actionable tasks: 227 executed, 1 up-to-date
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! edge-react-gui@1.1.3 android:release: `cd android && gradlew assembleRelease && cd ../`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the edge-react-gui@1.1.3 android:release script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Igor Igorevich Kim\AppData\Roaming\npm-cache\_logs\2018-04-23T05_31_44_968Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! edge-react-gui@1.1.3 android:release-install: `npm run android:clean && npm run android:release && cd android/app/build/outputs/apk && adb install app-release.apk; cd ../`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the edge-react-gui@1.1.3 android:release-install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Igor Igorevich Kim\AppData\Roaming\npm-cache\_logs\2018-04-23T05_31_45_003Z-debug.log

and this thing appear after I had installed bcoin "manually" by "yarn add bcoin"

> TransformError: C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui\node_modules\bcoin\lib\bcoin.js: require() must have a single string literal argument: C:\Users\Igor Igorevich Kim\Desktop\edge-react-gui\node_modules\bcoin\lib\bcoin.js:139
> 
> :app:bundleReleaseJsAndAssets FAILED

**Comment by paullinator** [comment]
The project will not build on Windows and this is an unsupported build environment. Sorry
