### ISSUE TITLE
Can not install repositories

### ISSUE THREAD

**Issue by StanislavSergeev** [EdgeApp/edge-react-gui#607]
I cloned this project and did "npm install".
However, It is always stopped after few seconds, but progress bar always shown and not continue anymore.

Stopped at this progress.

> fetchMetadata: sill pacote range manifest for parse-passwd@^1.0.0 fetched in 226ms

**Comment by paullinator** [comment]
Use yarn v1.3.2 or higher. NPM doesn’t work well

**Comment by StanislavSergeev** [comment]
I tried, but it doesn't work also.
It stopped progress while installing and my pc speed slower and slower.
Why this happen?

**Comment by StanislavSergeev** [comment]
Now work.

**Comment by Fliego** [comment]
Any updates?

**Comment by StanislavSergeev** [comment]
Not work

**Comment by paullinator** [comment]
What kind of computer are you on?

We’ve only tested this on Linux and MacOS. Windows is not confirmed to work.

**Comment by StanislavSergeev** [comment]
I am using MacOS. Can you help me remotely? using teamviewer or other.

**Comment by StanislavSergeev** [comment]
Please check my screenshot. Always freeze with this screen. I waited 1 hour and half.
[Screenshot](https://www.dropbox.com/s/bqsu4i6vu7anuwt/Screen%20Shot%202018-04-30%20at%202.32.49%20AM.png?dl=0)

**Comment by paullinator** [comment]
Hmm. I have at times experienced a build hang in the past. I honestly can't say what actually fixed it. React Native modules can be notorious as some of them build native code which can hang if you don't have proper tools installed for Xcode or if your Xcode environment is slightly messed up. Some things that have worked for me:

1. Make sure you have Xcode 9.2. If you do, then uninstall xcode, reboot, reinstall, then reboot again.
2. Make sure you don't have any extraneous environment variables in the terminal. This caused a problem for me at one point. Do a `printenv` and make sure it "looks normal". Hard to explain what that is, but during a build, xcode sets some env vars that are temporary and only used for that one specific build. I've had one instance where those env vars got "stuck" and were created on every terminal window launch. A reboot fixed that.
3. I know I'm able to build with these exact versions of build tools. Use these versions and see if you still have issues

```Baileys:lib paul$ npm -v
5.5.1
Baileys:lib paul$ node -v
v8.9.3
Baileys:lib paul$ yarn -v
1.5.1
Baileys:lib paul$ ```

**Comment by paullinator** [comment]
No comment in 90 days. Closing
