### ISSUE TITLE
yarn error: not found mymonero-core-js.git

### ISSUE THREAD

**Issue by dasenlinCode** [EdgeApp/edge-react-gui#998]
hi:
   when run yarn, i meet error:
**error** Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/Airbitz/mymonero-core-js.git
Directory: /Users/mac/EdgeApp/edge-react-gui
Output:
fatal: remote error: 
  Repository not found.

**Comment by paullinator** [comment]
We accidentally renamed git://github.com/Airbitz/mymonero-core-js.git to git://github.com/EdgeApp/mymonero-core-js.git

This is a dependency of edge-currency-monero which we're about to push an updated version for which should fix the problem. Apologize.

**Comment by paullinator** [comment]
Should be fixed using latest develop or master

https://github.com/EdgeApp/edge-react-gui/commit/05ef9eaa028c7febac1ee200ac1e34b38fb8c50d

**Comment by dasenlinCode** [comment]
Thanks a lot, it works.

**Comment by dasenlinCode** [comment]
Close this issue
